services:
  rabbitmq:
    image: rabbitmq:latest

  backend:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    environment:
      SECRET_KEY: secret!
      BROKER_URL: amqp://guest:guest@rabbitmq:5672//

  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./data/nginx:/var/log/nginx

  worker:
    build:
      context: ./
      dockerfile: docker/worker/Dockerfile
    environment:
      BROKER_URL: amqp://guest:guest@rabbitmq:5672//
    command: "celery -A worker worker -l info -P solo"
